name: deploy-pages

triggers:
  push:

jobs:
  deploy:
    image: alios-8u
    steps:
      - uses: checkout
      - uses: setup-env
        inputs:
          node-version: 20
          tnpm-version: 10
      - id: build-website
        run: |
          cd pages
          npm install --registry=https://registry.anpm.alibaba-inc.com
          bash build.sh
      - uses: deploy-pages
        inputs:
          deploy-dir: pages/build/
          production-branch: master
