//! Durable, workspace-resident copy of joi's CLI surface — written as
//! `{agent.workspace}/AGENTS.md` so ACP agents (Claude Code, Codex, etc.)
//! see joi's capabilities on every turn via the standard `AGENTS.md`
//! convention, independent of context length or compaction.
//!
//! The first-prompt `seed_manifest` still fires on every new (actor, scope)
//! pair and announces the current scope id; this file is the scope-agnostic
//! catalogue that augments it.
//!
//! The joi-controlled region is delimited by `<!-- BEGIN joi -->` /
//! `<!-- END joi -->` markers. Content outside the markers is preserved
//! across rewrites so the user (or other tooling) can append their own
//! instructions to the same AGENTS.md without losing them.

use std::io;
use std::path::Path;

const BEGIN_MARKER: &str = "<!-- BEGIN joi -->";
const END_MARKER: &str = "<!-- END joi -->";

/// Write or refresh the joi block inside `{workspace}/AGENTS.md`. Safe to
/// call on every agent spawn — cheap and idempotent.
pub fn ensure_agents_md(workspace: &Path, actor_id: &str) -> io::Result<()> {
    let path = workspace.join("AGENTS.md");
    let block = joi_block(actor_id);
    let new_content = match std::fs::read_to_string(&path) {
        Ok(existing) => update_block(&existing, &block),
        Err(e) if e.kind() == io::ErrorKind::NotFound => {
            let mut out = String::with_capacity(block.len() + 1);
            out.push_str(&block);
            out.push('\n');
            out
        }
        Err(e) => return Err(e),
    };
    std::fs::write(&path, new_content)
}

fn update_block(existing: &str, new_block: &str) -> String {
    if let (Some(begin), Some(end_rel)) = (
        existing.find(BEGIN_MARKER),
        existing[existing
            .find(BEGIN_MARKER)
            .map(|i| i + BEGIN_MARKER.len())
            .unwrap_or(0)..]
            .find(END_MARKER),
    ) {
        let end = existing.find(BEGIN_MARKER).unwrap() + BEGIN_MARKER.len() + end_rel;
        let end_past = end + END_MARKER.len();
        let mut out = String::with_capacity(existing.len() + new_block.len());
        out.push_str(&existing[..begin]);
        out.push_str(new_block);
        out.push_str(&existing[end_past..]);
        return out;
    }
    let mut out = existing.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }
    if !out.is_empty() && !out.ends_with("\n\n") {
        out.push('\n');
    }
    out.push_str(new_block);
    out.push('\n');
    out
}

fn joi_block(actor_id: &str) -> String {
    format!(
        "{BEGIN_MARKER}\n\
## Joi multi-actor runtime\n\
\n\
You are an ACP agent running inside the Joi multi-actor server.\n\
This section is auto-generated by joi and will be rewritten on each agent\n\
start. Anything outside the `BEGIN joi` / `END joi` markers is preserved.\n\
\n\
### Identity\n\
\n\
- `actor_id`: `{actor_id}`\n\
- You speak as this actor on the server; other actors (humans or agents)\n\
  see your events attributed to this id.\n\
\n\
### Environment\n\
\n\
These variables are already set in your process env:\n\
\n\
- `JOI_SERVER` — WebSocket URL of the joi server.\n\
- `JOI_DAEMON_SOCKET` — local daemon socket used automatically by `joi` CLI when available.\n\
- `JOI_ACTOR`  — your actor id ({actor_id}).\n\
- `JOI_SCOPE_ID` — current thread or channel scope id for this turn.\n\
- `JOI_SCOPE_KIND` — `thread` or `channel` for this turn.\n\
- `JOI_TURN_ID` — current Joi turn id.\n\
- `JOI_TRIGGER_ACTOR` — actor id of the human or agent that triggered this turn.\n\
- `AGENTX_CHANNEL_ID` — channel id that owns the current scope.\n\
\n\
### Current scope\n\
\n\
A turn always runs in a *scope* (a `thread` or a `channel`). The first prompt\n\
in each provider session is prefixed with the current `actor id` and\n\
`current scope = thread:<id>` or `current scope = channel:<id>`; command\n\
agents without resume support receive that prefix on every turn. Copy that id\n\
verbatim when you pass low-level `--in <scope_id>` commands below. If a user\n\
asks for channel or thread history, query Joi first; do not answer from the\n\
local profile memory directory.\n\
Message targets use a separate canonical grammar: `#<channel_id>` for a\n\
channel and `#<channel_id>:<root_event_id>` for a thread. If you only have a\n\
thread scope id, run `joi --json thread list` and find the row with that id;\n\
its `channelId` and `rootEventId` form the message target.\n\
\n\
### Read-only CLI\n\
\n\
Shell out to `joi --json ...` for server state. `--json` returns machine-\n\
readable output; drop it for pretty output.\n\
\n\
Joi does not execute arbitrary assistant-side tool calls such as `Skill`.\n\
Use your own built-in tools or shell commands, and use `joi` / `a1` CLI\n\
commands directly for server or Aone state.\n\
\n\
```\n\
joi --json event list --in \"$JOI_SCOPE_ID\" --limit 200        # thread scope\n\
joi --json event list --in \"$JOI_SCOPE_ID\" --channel --limit 200  # channel scope\n\
joi --json message read --target '#<channel_id>'\n\
joi --json message read --target '#<channel_id>:<root_event_id>'\n\
joi --json message read --target '#<channel_id>:<root_event_id>' --before <event_id>\n\
joi --json message search --query \"keyword\" --target '#<channel_id>:<root_event_id>'\n\
joi --json message check                               # drain directed inbox\n\
joi --json thread list\n\
joi --json channel list\n\
joi --json actor list\n\
joi --json agent list\n\
joi --json reminder list\n\
joi --json artifact get <art_id|artifact://...>\n\
joi --json artifact read <art_id> [--max-bytes N]\n\
```\n\
\n\
### Write CLI\n\
\n\
Send messages, DMs, attachments, and reminders:\n\
\n\
```\n\
joi --json message send --target '#<channel_id>' --text \"thread title\"   # returns event.id\n\
joi --json thread create --channel <channel_id> --root-event <event_id> --title \"thread title\"\n\
joi --json message send --target '#<channel_id>:<root_event_id>' <<'JOIMSG'\n\
message body\n\
JOIMSG\n\
joi --json message send --target dm:<actor_id> <<'JOIMSG'\n\
private note\n\
JOIMSG\n\
joi --json handoff <actor_id> --in <scope_id> --message \"please take this\"\n\
joi --json ask-user-question --title \"Choose option\" --question \"Which option?\" \\\n\
    --choice a=A --choice b=B\n\
joi --json request-approval --title \"Approval required\" --reason \"Run the deploy command\"\n\
joi --json attachment upload --target '#<channel_id>:<root_event_id>' --path <file>\n\
joi --json artifact publish --in <scope_id> [--channel] \\\n\
    --name <file> [--media-type <type>] (--text <body> | --file <path>)\n\
joi --json reminder schedule --target '#<channel_id>:<root_event_id>' \\\n\
    --title \"follow up\" --delay-seconds 3600\n\
```\n\
\n\
Use `dm:<actor_id>` for private messages. `handoff` is responsibility\n\
transfer in the current scope, not a DM target, and aliases such as\n\
`dm:@actor` are not supported. Thread targets are rooted at channel events;\n\
thread-in-thread targets are not supported.\n\
\n\
Use `joi --help` and `joi <subcommand> --help` for the full surface.\n\
{END_MARKER}"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_write_just_joi_block() {
        let out = update_block("", &joi_block("actor_demo"));
        assert!(out.contains("actor_demo"));
        assert!(out.contains("JOI_SCOPE_ID"));
        assert!(out.contains(BEGIN_MARKER));
        assert!(out.contains(END_MARKER));
    }

    #[test]
    fn preserves_user_content_outside_markers() {
        let existing = format!(
            "# My project rules\n\nStyle: tabs.\n\n{BEGIN_MARKER}\nold joi content\n{END_MARKER}\n\n## Postscript\n\nMore notes.\n"
        );
        let out = update_block(&existing, &joi_block("actor_x"));
        assert!(out.contains("My project rules"));
        assert!(out.contains("Style: tabs."));
        assert!(out.contains("Postscript"));
        assert!(out.contains("More notes."));
        assert!(out.contains("actor_x"));
        assert!(!out.contains("old joi content"));
    }

    #[test]
    fn appends_block_when_no_markers() {
        let existing = "# Existing file\n\nHello.\n";
        let out = update_block(existing, &joi_block("actor_y"));
        assert!(out.starts_with("# Existing file"));
        assert!(out.contains("actor_y"));
        assert!(out.contains(BEGIN_MARKER));
    }

    #[test]
    fn idempotent_across_repeated_writes() {
        let once = update_block("", &joi_block("actor_z"));
        let twice = update_block(&once, &joi_block("actor_z"));
        assert_eq!(once, twice);
    }
}
