[package]
name = "joi-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "joi-server"
path = "src/main.rs"

[dependencies]
proto = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
futures-util = { workspace = true }
